import streamlit as st
import pandas as pd
import numpy as np

# Page config for a wide, professional dashboard look
st.set_page_config(page_title="GovFlow-AI Dashboard", layout="wide")

# --- HEADER ---
st.title("🏛️ GovFlow-AI: Policy Simulation & Trade-off Engine")
st.markdown("Transforming noisy, delayed public education data into actionable governance insights.")
st.divider()

# --- SIDEBAR: POLICY & AI CONTROLS ---
st.sidebar.header("⚙️ Plug-and-Play AI Engine")
selected_model = st.sidebar.selectbox("Active Prediction Model", ["Logistic Regression", "Random Forest"])

st.sidebar.header("💰 Budget Allocation Simulation")
st.sidebar.markdown("Adjust policy funding to see predicted trade-offs.")
budget_transport = st.sidebar.slider("Transport Subsidy (Crores)", 0, 50, 10)
budget_meals = st.sidebar.slider("Mid-Day Meal Expansion (Crores)", 0, 50, 15)

# --- LOAD DATA ---
# This loads the CSV generated by the pipeline
@st.cache_data
def load_data():
    try:
        return pd.read_csv("students_cleaned.csv")
    except FileNotFoundError:
        st.error("Data missing. Please run `data_pipeline.py` first.")
        return pd.DataFrame()

df = load_data()

# --- MAIN DASHBOARD AREA ---
col1, col2 = st.columns(2)

with col1:
    st.subheader("Current Regional Baseline")
    st.markdown("Data based on historical records.")
    # Placeholder for a metric or chart
    st.metric(label="Baseline High-Risk Students", value=f"{len(df[df['Dropped_Out'] == 1])}")
    
with col2:
    st.subheader("Simulated Policy Impact")
    st.markdown(f"Using **{selected_model}** | Transport: ₹{budget_transport}Cr | Meals: ₹{budget_meals}Cr")
    # Placeholder metric for what happens after the sliders move
    # Tomorrow, this will hook into YOUR math function
    st.metric(label="Projected High-Risk Students", value="Waiting for ML Engine...", delta="-8.2%")

st.divider()

# --- HUMAN IN THE LOOP (Crucial Hackathon Feature) ---
st.header("🛑 Human-in-the-Loop Override")
st.markdown("Interrupt the AI and force a recalculation based on offline knowledge.")

col_override1, col_override2 = st.columns(2)

with col_override1:
    override_id = st.number_input("Target Student/District ID", min_value=1001, max_value=6000, step=1)
    override_action = st.selectbox("Force Risk Level", ["Mark as Safe", "Mark as High Risk"])

with col_override2:
    override_reason = st.text_input("Reason for Intervention (Audit Log)")
    if st.button("Execute Override"):
        if override_reason:
            st.success(f"Audit Logged: Override applied for ID {override_id}. Reason: {override_reason}")
            # Tomorrow, this button will actually change the dataframe in real time
        else:
            st.warning("Please provide a reason to maintain governance transparency.")
